// src/components/preact/ThemeSwitch.tsx
/**
 * Replica de ThemeSwitch.astro en Preact. No está instanciado
 *
 * import ThemeSwitchPreact from '../components/preact/ThemeSwitch'
 * <ThemeSwitchReact client:load />
 */
import { useEffect, useState } from 'preact/hooks'
import type { FunctionalComponent } from 'preact'

export default function ThemeToggle(): FunctionalComponent {
	const [theme, setTheme] = useState(localStorage.getItem('theme') ?? 'light')

	const handleClick = () => {
		console.log('hola2')
		setTheme(theme === 'light' ? 'dark' : 'light')
	}

	useEffect(() => {
		if (theme === 'dark') {
			document.documentElement.classList.add('dark')
		} else {
			document.documentElement.classList.remove('dark')
		}
		localStorage.setItem('theme', theme)
	}, [theme])

	return <button onClick={handleClick}>{theme === 'light' ? '🌙' : '🌞'}</button>
}

// src/components/vue/ThemeSwitch.vue
<script lang="ts">
/**
 * Replica de ThemeSwitch.astro en Vue.js. No está instanciado
 *
 * import ThemeSwitchVue from '../components/vue/ThemeSwitch.vue'
 * <ThemeSwitchVue client:load />
 */
import { defineComponent } from 'vue'

export default defineComponent({
	data() {
		return {
			theme: localStorage.getItem('theme') || 'light'
		}
	},
	methods: {
		handleClick() {
			this.theme = this.theme === 'light' ? 'dark' : 'light'
		}
	},
	watch: {
		theme(newTheme) {
			if (newTheme === 'dark') {
				document.documentElement.classList.add('dark')
			} else {
				document.documentElement.classList.remove('dark')
			}
			localStorage.setItem('theme', newTheme)
		}
	}
})
</script>

<template>
	<div>
		<button @click="handleClick">{{ theme === 'light' ? '🌙' : '🌞' }}</button>
	</div>
</template>

<style></style>
